### ISSUE TITLE
Broken encoding of Unicode updates from the command line

### ISSUE THREAD

**Issue by astanin** [jgoerzen/twidge#12]
1.0.2 prints Unicode tweets correctly, but corrupts them when sending an update from the command line

    $ twidge update 'unicode message'

An example: http://twitter.com/jetxee/status/15322966107
Instead of: "... проверка twidge 1.0.2"

Sending an update from the stdin works correctly:

    $ twidge update
    unicode message^D

**Comment by muzzol** [comment]
I've hit this bug with version 1.1.2

pipeing workaround works but I've found another problem, if the string contains newlines it gets trimmed.

for example:
```
TEXT="one
two
three"

echo "$TEXT" | twidge update
```

just post "one"

**Comment by jgoerzen** [comment]
Did 09c59c20a35ec5f8ccd71596aad68f52fbd82559 not fix this?

**Comment by jgoerzen** [comment]
In fact, I believe 09c59c2 should have fixed this.
