### ISSUE TITLE
trying to install 1.1.0 getting libffi5 not installable error

### ISSUE THREAD

**Issue by fredzannarbor** [jgoerzen/twidge#53]
Tried this a couple of different ways -- always run into this.  Ubuntu 12.04 LTS.

bitnami@ip-10-77-13-28:~$ sudo dpkg -i twidge_1.1.0_amd64_wheezy.deb
Selecting previously unselected package twidge.
(Reading database ... 85433 files and directories currently installed.)
Unpacking twidge (from twidge_1.1.0_amd64_wheezy.deb) ...
dpkg: dependency problems prevent configuration of twidge:
 twidge depends on libffi5 (>= 3.0.4); however:
  Package libffi5 is not installed.
dpkg: error processing twidge (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 twidge

**Comment by jgoerzen** [comment]
You will need to recompile or install the missing library.
