### ISSUE TITLE
Fails to post updates with unicode characters

### ISSUE THREAD

**Issue by nodiscc** [jgoerzen/twidge#58]
Twidge fails to post messages with unicode characters in them:

    ↳ twidge update "▶ Cypress Hill - Tequila Sunrise - YouTube https://www.youtube.com/watch?v=QrWnH7cV_-c"
    twidge: Enum.toEnum{Word8}: tag (9654) is outside of bounds (0,255)

Nothing is posted after running this command.

There's a similar problem at https://github.com/jaor/xmobar/issues/106 with a patch available.

**Comment by HackerGaucho** [comment]
same with portuguese

**Comment by jgoerzen** [comment]
What version was this with?  09c59c20a35ec5f8ccd71596aad68f52fbd82559 should have fixed this

**Comment by nodiscc** [comment]
@jgoerzen It was a loooong time ago and I don't use twidge anymore. I'll close this since you seem to have fixed it. Thanks!
