### ISSUE TITLE
Bad Reponse 410

### ISSUE THREAD

**Issue by rdsplus** [jgoerzen/twidge#64]
Hi I just installed twidge on my raspberry PI and when i try to use it I am getting

pi@raspberrypi ~ $ sudo twidge -d lsrecent
CP /root/.twidgerc exists? True
Sending request: ReqHttp {version = HTTP/1.1, ssl = True, host = "api.twitter.com", port = 443, method = GET, reqHeaders = Authorization=OAuth%20oauth_signature%3D%22AGp2wGWFXvCjIV4%252BHSHH5OwExqI%253D%22%2Coauth_consumer_key%3D%22pzWekpM5IRh7HaKc9syEw%22%2Coauth_nonce%3D%221402789743%22%2Coauth_timestamp%3D%221425428603%22%2Coauth_signature_method%3D%22HMAC-SHA1%22%2Coauth_version%3D%221.0%22%2Coauth_token%3D%223059712134-cSLtmepbaoVqpOMNksA11wVFvTEu1uptExDgumf%22, pathComps = ["","1","statuses","friends_timeline.xml"], qString = page=1, reqPayload = Empty}
Got response: (410,"",[],"")
twidge: user error (Bad response: 410)

is it broken or is it just me?

**Comment by jgoerzen** [comment]
I doubt twidge is broken.  What version are you using?

**Comment by rdsplus** [comment]
Hi John,

1.0.8 on ARM

**Comment by jgoerzen** [comment]
That version speaks only Twitter's old API.  It is not possible to use it anymore.  Upgrading will fix your issue.
