### ISSUE TITLE
Install on Raspbian: Invalid package name (character not allowed)

### ISSUE THREAD

**Issue by java-artisan** [jgoerzen/twidge#65]
Twidge can not be installed on Raspbian due to an invalid character in the package name (0010 ?). See the included screenshot. It's the name of a dependency libnewp<...>12.

![screenshot - 04102015 - 10 29 04 am](https://cloud.githubusercontent.com/assets/979063/7084378/e7a296d4-df6c-11e4-886f-1f44a5ae62df.png)

**Comment by jgoerzen** [comment]
I am sorry you are having an issue, but I have nothing to do with the Raspbian packages.  Please contact them.

**Comment by java-artisan** [comment]
Right; I assumed you were also shipping those. 

Thanks !

**Comment by java-artisan** [comment]
There you go: https://bugs.launchpad.net/raspbian/+bug/1442608
